default:
  image: node:latest
  before_script:
    - yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

stages:
  - test lint build
  - render
  - lint html
  - deploy

test:
  stage: test lint build
  script:
    - yarn run test

lint:
  stage: test lint build
  script:
    - yarn run lint

build:
  stage: test lint build
  script:
    - yarn run generate
  artifacts:
    paths:
      - dist/

pdf:
  stage: render
  image:
    name: zenika/alpine-chrome:latest
    entrypoint: [""]
  before_script: []
  script:
    - ci/generate-pdf.sh
  artifacts:
    paths:
      - "*.pdf"

screenshot:
  stage: render
  image:
    name: alekzonder/puppeteer:latest
  before_script: []
  script:
    - node ci/generate-screenshot.js
  artifacts:
    paths:
      - "*.png"

html proofer:
  stage: lint html
  image: ruby:2.7
  before_script:
    - bundle install
  script:
    - ci/run-html-proofer.rb

pages:
  stage: deploy
  script:
    - ci/pages-preparation.sh
  artifacts:
    paths:
      - public
  only:
    - master
