image: node:latest

stages:
  - test lint build
  - deploy

before_script:
  - yarn

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:
  stage: test lint build
  script:
    - yarn run test

lint:
  stage: test lint build
  script:
    - yarn run lint

build:
  stage: test lint build
  script:
    - yarn run generate
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - ci/pages-preparation.sh
  artifacts:
    paths:
      - public
  only:
    - master
