image: node:latest

stages:
  - test lint build
  - render
  - deploy

before_script:
  - yarn

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:
  stage: test lint build
  script:
    - yarn run test

lint:
  stage: test lint build
  script:
    - yarn run lint

build:
  stage: test lint build
  script:
    - yarn run generate
  artifacts:
    paths:
      - dist/

pdf:
  stage: render
  image:
    name: zenika/alpine-chrome:latest
    entrypoint: [""]
  before_script: []
  script:
    - ci/generate-pdf.sh
  artifacts:
    paths:
      - "*.pdf"

screenshot:
  stage: render
  image:
    name: zenika/alpine-chrome:68
    entrypoint: [""]
  before_script: []
  script:
    - ci/generate-screenshot.sh
  artifacts:
    paths:
      - "*.png"

pages:
  stage: deploy
  script:
    - ci/pages-preparation.sh
  artifacts:
    paths:
      - public
  only:
    - master
